name: 'Build .NET installer'
description: 'Build .NET installer for riscv64'
inputs: 
  repository:
    description: 'Repository of .Net installer'
    default: https://github.com/dotnet/installer
  branch:
    description: 'Branch to build'
    required: true
  aspnetcore_version:
    description: 'aspnetcore version'
    required: true
  runtime_version:
    description: 'Runtime version'
    required: true
  sdk_version: 
    description: 'SDK version'
    required: true
  surfix:
    description: 'info to append to the installer name'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Clone repository
      run: git clone --depth 1 -b ${{ inputs.branch }} ${{ inputs.repository }}
      shell: bash
    - name: Build installer
      shell: bash
      run: |
        cd installer
        sed -i "s|linux-arm64|linux-riscv64|" src/redist/targets/GenerateBundledVersions.targets
        sed -i "s|linux-arm64|linux-riscv64|" src/SourceBuild/content/eng/bootstrap/buildBootstrapPreviouslySB.csproj
        sed -i s'|ppc64le|riscv64|' Directory.Build.props
        sed -i s'|ppc64le|riscv64|' src/SourceBuild/content/Directory.Build.props
        sed -i s'|ppc64le|riscv64|' src/redist/targets/Crossgen.targets
        sed -i s"|<clear />|<clear />\n<add key='local' value='${{ env.PACKAGESDIR }}' />|" NuGet.config
        ./build.sh --ci -c Release -a riscv64 /p:HostRid=linux-x64 /p:PublicBaseURL=file://${{ env.DOWNLOADDIR }}/
        cp artifacts/packages/Release/Shipping/dotnet-sdk-*-linux-riscv64.tar.gz ${{ env.OUTPUTDIR }}
        cp artifacts/packages/Release/Shipping/dotnet-sdk-*-linux-riscv64.tar.gz.sha512 ${{ env.OUTPUTDIR }}
    - name: Upload .NET installer
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-sdk-linux-riscv64-${{ inputs.surfix }}
        path: ${{ env.OUTPUTDIR }}/dotnet-sdk-*-linux-riscv64.tar.gz*