name: Build .NET SDK

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      main
env:
  PACKAGESDIR: ${{ github.workspace }}/packages
  DOWNLOADDIR: ${{ github.workspace }}/downloads
  OUTPUTDIR: ${{ github.workspace }}/output
  RUNTIME_VERSION: 8.0.0-rtm.23531.3
  SDK_VERSION: 8.0.100-rtm.23551.6
  ASPNETCORE_VERSION: 8.0.0-rtm.23531.12
  ROOTFS_DIR: /crossrootfs/riscv64

jobs:
  build_dotnet_coreclr:
    name: Build .NET with CoreCLR Backend
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-22.04-cross-riscv64

    steps:
      - uses: actions/checkout@v4
      - name: build .Net Runtime With CoreCLR Backend
        uses: ./.github/actions/build-runtime
        with:
          branch: v8.0.0
          repository: https://github.com/dotnet/runtime
          runtime_version: ${{ env.RUNTIME_VERSION }}
      - name: build .Net SDK
        uses: ./common-steps@build_SDK
        with:
          branch: v8.0.100
          repository: https://github.com/dotnet/sdk
          sdk_version: ${{ env.SDK_VERSION }}
      - name: build .Net aspnetcore
        uses: ./common-steps@build_aspnetcore
        with:
          branch: v8.0.0
          repository: https://github.com/dotnet/aspnetcore
          aspnetcore_version: ${{ env.ASPNETCORE_VERSION }}
          runtime_version: ${{ env.RUNTIME_VERSION }}
      - name: build .Net installer
        uses: ./common-steps@build_installer
        with:
          branch: v8.0.100
          repository: https://github.com/dotnet/installer
          aspnetcore_version: ${{ env.ASPNETCORE_VERSION }}
          runtime_version: ${{ env.RUNTIME_VERSION }}
          sdk_version: ${{ env.SDK_VERSION }}
      - name: Upload .NET installer
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-sdk-linux-riscv64
          path: ${{ env.OUTPUTDIR }}/dotnet-sdk-*-linux-riscv64.tar.gz*
